import { Link } from "@tanstack/react-router";
import { ArrowRight, Box, Building2, CarFront, PackageCheck, Ship, Warehouse } from "lucide-react";
import { Button } from "@/components/ui/button";
import { audiences, Breadcrumbs, ContactDetails, ContactForm, CtaSection, images, PageHero, ProcessTimeline, RouteVisualization, SectionHeader, ServiceGrid } from "@/components/site";

export function HomePage() { return <>
  <section className="page-hero min-h-[92vh]"><img src={images.portHero} alt="Cargo vessel at a U.S. container terminal" width={1920} height={1080}/><div className="page-hero-overlay"/><div className="site-container relative z-10 flex min-h-[92vh] items-end pb-16 pt-36 lg:pb-20"><div className="max-w-5xl"><p className="eyebrow light">Global supply chain</p><h1 className="display-title mt-6 text-on-dark">Connecting supply.<br/><span className="text-brand-soft">Moving business.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-on-dark-muted">End-to-end procurement, logistics, warehousing and distribution solutions connecting the United States with West Africa.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild variant="brand" size="xl"><Link to="/contact">Request a quote<ArrowRight/></Link></Button><Button asChild variant="outlineLight" size="xl"><Link to="/services">Explore our services</Link></Button></div><div className="mt-12 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.18em] text-on-dark-muted"><span>North America</span><span className="h-px w-12 bg-brand"/><span className="size-1.5 bg-signal"/><span className="h-px w-12 bg-brand-soft"/><span>West Africa</span></div></div></div></section>
  <section className="bg-background"><div className="site-container grid gap-12 py-20 lg:grid-cols-[1fr_1.05fr] lg:items-center lg:py-32"><div><SectionHeader eyebrow="About Cogent" title="Your U.S. partner for global supply."/><Button asChild variant="brand" size="xl" className="mt-8"><Link to="/about">About Cogent<ArrowRight/></Link></Button></div><div className="border-l-2 border-signal pl-7 text-base leading-8 text-muted-foreground lg:pl-12"><p>Cogent Distributing LLC is your trusted, one-stop partner for supply chain solutions from the United States to West Africa.</p><p className="mt-5">We specialize in end-to-end procurement, secure warehousing and reliable logistics. Whether you need to source commercial inventory or ship personal cargo, we manage the process with professional coordination and oversight.</p><p className="mt-5">We also serve as a dependable, on-the-ground hub for international clients who require professional representation and local oversight within the United States.</p></div></div></section>
  <section className="bg-on-dark py-20 lg:py-28"><div className="site-container"><SectionHeader eyebrow="Our services" title="From source to destination."/><div className="mt-12"><ServiceGrid/></div></div></section>
  <section className="bg-navy py-20 text-on-dark lg:py-28"><div className="site-container"><SectionHeader light eyebrow="Connected markets" title="From North America to West Africa." text="Cogent helps bridge the distance between U.S. supply and West African demand through coordinated procurement, logistics and distribution solutions."/><RouteVisualization/></div></section>
  <section className="py-20 lg:py-28"><div className="site-container"><SectionHeader eyebrow="How it works" title="One partner. One connected process."/><div className="mt-14"><ProcessTimeline/></div><Button asChild variant="brand" size="xl" className="mt-12"><Link to="/logistics">How our logistics work<ArrowRight/></Link></Button></div></section>
  <section className="bg-on-dark py-20 lg:py-28"><div className="site-container"><SectionHeader eyebrow="Who we serve" title="Built for different requirements."/><div className="mt-12 border-t border-border">{audiences.map(([name,text],i)=><div key={name} className="grid gap-4 border-b border-border py-7 sm:grid-cols-[4rem_1fr_1.2fr] sm:items-center"><span className="service-index">0{i+1}</span><h3 className="text-xl font-bold uppercase text-navy">{name}</h3><p className="text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></div></section><CtaSection/>
  </>; }

export function AboutPage() { const values=["Transparency","Efficiency","Reliability","Professionalism","Trusted Local Expertise"]; return <><PageHero eyebrow="About Cogent" title="Built to connect markets." text="A U.S.-based supply-chain partner connecting procurement, logistics and international commerce."/><Breadcrumbs current="About"/><section className="py-20 lg:py-28"><div className="site-container grid gap-14 lg:grid-cols-2"><SectionHeader eyebrow="Who we are" title="Professional coordination. Connected outcomes."/><div className="space-y-5 leading-8 text-muted-foreground"><p>Cogent Distributing LLC is a U.S.-based supply-chain, procurement, logistics, warehousing, automobile sourcing, shipping and distribution company connecting the United States with West Africa.</p><p>We exist to simplify international procurement and logistics through clear coordination, dependable local oversight and one connected process.</p></div></div></section><section className="bg-navy py-20 text-on-dark lg:py-28"><div className="site-container grid gap-12 lg:grid-cols-2"><QuoteBlock label="Mission">“Our mission is to provide seamless, end-to-end supply chain solutions that bridge the United States and West Africa. We are dedicated to delivering secure procurement, reliable logistics, and dependable on-the-ground U.S. representation for both commercial and personal cargo clients through transparency, efficiency, and trusted local expertise.”</QuoteBlock><QuoteBlock label="Vision">“Our vision is to be the premier, undisputed bridge for transatlantic trade between North America and West Africa, recognized for transforming complex international logistics into simple, frictionless, and accessible solutions for global growth.”</QuoteBlock></div></section><section className="py-20 lg:py-28"><div className="site-container"><SectionHeader eyebrow="Core values" title="The standard behind every requirement."/><div className="mt-12 grid border-l border-t border-border sm:grid-cols-2 lg:grid-cols-5">{values.map((v,i)=><div className="border-b border-r border-border p-7" key={v}><span className="service-index">0{i+1}</span><h3 className="mt-8 font-bold uppercase text-navy">{v}</h3></div>)}</div><div className="mt-20 grid gap-10 lg:grid-cols-[1fr_1.1fr] lg:items-center"><img src={images.warehouseImage} alt="Organized warehouse and cargo preparation" loading="lazy" width={1600} height={1067}/><div><SectionHeader eyebrow="U.S. representation" title="Local oversight for international clients." text="Cogent serves as a dependable, on-the-ground U.S. hub for clients who need professional representation across procurement, warehousing and logistics coordination."/></div></div></div></section><CtaSection/></>; }
function QuoteBlock({label,children}:{label:string;children:React.ReactNode}) { return <article className="border-t-2 border-brand pt-7"><p className="eyebrow light">{label}</p><blockquote className="mt-7 text-xl font-medium leading-9 text-on-dark">{children}</blockquote></article>; }

export function ServicesPage() { return <><PageHero eyebrow="Services" title="Solutions built around the supply chain." text="A connected set of services designed to move requirements from sourcing through distribution." image={images.freightImage}/><Breadcrumbs current="Services"/><section className="py-20 lg:py-28"><div className="site-container"><SectionHeader eyebrow="Capabilities" title="One connected service system."/><div className="mt-12"><ServiceGrid/></div></div></section><SupplyChain/><CtaSection/></>; }

const detailData={
 procurement:{eyebrow:"Procurement & sourcing",title:"Source with confidence.",text:"Professional procurement support for commercial goods, industrial tools, retail items, mechanical equipment, automotive components and specialized requirements.",image:images.freightImage,items:["Commercial goods","Industrial tools","Retail items","Mechanical equipment","Automotive components","Specialized sourcing"],flow:["Requirement","Sourcing","Procurement","Consolidation","Shipping"],cta:"Request procurement assistance"},
 automotive:{eyebrow:"Automobile logistics",title:"From vehicle search to international shipping.",text:"Cogent provides automobile procurement and international shipping coordination through one professionally managed process.",image:images.automotiveImage,items:["Vehicle sourcing","Purchase coordination","Vehicle preparation","Shipping coordination","Automotive parts","International logistics"],flow:["Requirement","Vehicle sourcing","Purchase coordination","Preparation","Shipping"],cta:"Discuss a vehicle requirement"},
 shipping:{eyebrow:"Shipping & freight",title:"Move more. Move smarter.",text:"Freight solutions selected around the nature, scale and urgency of a cargo requirement.",image:images.portHero,items:["Ocean Freight|Scalable international transportation for larger cargo requirements.","Air Freight|A faster freight option for suitable cargo.","Bulk Shipping|Designed around larger-volume shipments.","Groupage|Shared-container shipping for customers who do not require an entire container."],flow:["Cargo","Warehouse","Consolidation","Freight","Destination"],cta:"Discuss a freight requirement"},
 warehousing:{eyebrow:"Warehousing & packing",title:"Protect what you move.",text:"Professional cargo preparation, storage and consolidation designed around secure international movement.",image:images.warehouseImage,items:["Professional Packing|Secure preparation for international movement.","Heavy-Duty Crating|Protective crating for suitable equipment and cargo.","Warehousing|Storage and cargo management.","Consolidation|Combining shipments to support efficient transportation."],flow:["Receive","Store","Pack","Consolidate","Prepare"],cta:"Discuss a warehousing requirement"},
 distribution:{eyebrow:"Distribution & logistics",title:"A connected approach to distribution.",text:"Cogent coordinates the linked stages of the supply chain, from procurement and warehousing through freight and distribution.",image:images.freightImage,items:["Procurement","Warehouse","Consolidation","Freight","Distribution"],flow:["Procurement","Warehouse","Consolidation","Freight","Distribution"],cta:"Discuss a logistics requirement"},
} as const;
export function ServiceDetailPage({kind}:{kind:keyof typeof detailData}) { const d=detailData[kind]; return <><PageHero eyebrow={d.eyebrow} title={d.title} text={d.text} image={d.image}/><Breadcrumbs current={d.eyebrow}/><section className="py-20 lg:py-28"><div className="site-container"><SectionHeader eyebrow="What we coordinate" title="Built around your requirement."/><div className="mt-12 grid border-l border-t border-border sm:grid-cols-2 lg:grid-cols-3">{d.items.map((raw,i)=>{const [title,text]=raw.split("|");return <article key={raw} className="border-b border-r border-border p-7 lg:p-9"><span className="service-index">0{i+1}</span><h3 className="mt-6 text-lg font-bold uppercase text-navy">{title}</h3>{text&&<p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p>}</article>})}</div></div></section><section className="bg-on-dark py-20 lg:py-28"><div className="site-container"><SectionHeader eyebrow="Connected process" title="From requirement to movement."/><Flow labels={d.flow}/><Button asChild variant="brand" size="xl" className="mt-12"><Link to="/contact">{d.cta}<ArrowRight/></Link></Button></div></section><CtaSection/></>; }

function Flow({labels}:{labels:readonly string[]}) { return <div className="mt-12 grid gap-px bg-border lg:grid-cols-5">{labels.map((label,i)=><div key={label} className="relative bg-card p-6"><span className="service-index">0{i+1}</span><p className="mt-5 text-sm font-bold uppercase text-navy">{label}</p>{i<labels.length-1&&<ArrowRight className="absolute -right-3 top-1/2 z-10 size-6 bg-signal p-1 text-on-dark"/>}</div>)}</div>; }
function SupplyChain(){return <section className="bg-navy py-20 text-on-dark lg:py-28"><div className="site-container"><SectionHeader light eyebrow="Supply chain" title="Source. Prepare. Store. Consolidate. Ship. Distribute."/><RouteVisualization/></div></section>}

export function IndustriesPage(){const icons=[PackageCheck,Building2,Warehouse,Box,Ship];return <><PageHero eyebrow="Industries" title="Serving different needs. One standard of service." text="Flexible procurement and logistics coordination for five distinct customer groups." image={images.warehouseImage}/><Breadcrumbs current="Industries"/><section className="py-20 lg:py-28"><div className="site-container space-y-0">{audiences.map(([name,text],i)=>{const Icon=icons[i] ?? PackageCheck;return <article key={name} className="grid gap-6 border-b border-border py-12 md:grid-cols-[6rem_1fr_1fr] md:items-center"><div className="flex items-center gap-3 text-brand"><Icon/><span className="service-index">0{i+1}</span></div><h2 className="text-3xl font-extrabold uppercase text-navy">{name}</h2><p className="leading-7 text-muted-foreground">{text}</p></article>})}</div></section><CtaSection/></>}
export function LogisticsPage(){return <><PageHero eyebrow="Our logistics process" title="Logistics, without the guesswork." text="A clear five-stage approach bringing procurement, preparation, freight and final coordination into one connected process." image={images.freightImage}/><Breadcrumbs current="Logistics"/><section className="py-20 lg:py-28"><div className="site-container"><SectionHeader eyebrow="One connected process" title="Five stages. Professional oversight."/><div className="mt-16"><ProcessTimeline detailed/></div></div></section><section className="bg-navy py-20 text-on-dark"><div className="site-container"><SectionHeader light eyebrow="The connection" title="North America to West Africa." text="A conceptual bridge between supply and demand, supported by coordinated sourcing, preparation and movement."/><RouteVisualization/></div></section><CtaSection/></>}
export function CaseStudiesPage(){return <><PageHero eyebrow="Case studies" title="Real requirements. Real logistics." text="Verified project stories will document the requirement, coordination and outcome without compromising client trust."/><Breadcrumbs current="Case Studies"/><section className="py-24 lg:py-36"><div className="site-container"><div className="mx-auto max-w-3xl border-y border-border py-16 text-center"><span className="service-index">Project library</span><h2 className="section-title mt-6 text-navy">Case studies coming soon.</h2><p className="mx-auto mt-6 max-w-xl leading-8 text-muted-foreground">Verified project stories will be added as they become available. Each story will clearly identify the project context, service, challenge, solution and result.</p><Button asChild variant="brand" size="xl" className="mt-9"><Link to="/contact">Discuss your requirement<ArrowRight/></Link></Button></div></div></section></>}
export function ContactPage(){return <><PageHero eyebrow="Contact / request a quote" title="Let's move your requirement forward." text="Tell us what you need to source, prepare or move. Cogent will help identify the next step."/><Breadcrumbs current="Contact"/><section className="py-20 lg:py-28"><div className="site-container grid gap-14 lg:grid-cols-[.72fr_1.28fr]"><div><SectionHeader eyebrow="Contact Cogent" title="Start the conversation."/><div className="mt-10"><ContactDetails/></div></div><div><ContactForm/></div></div></section></>}

export function LegalPage({type}:{type:"privacy"|"terms"}){const privacy=["Information collected","How information is used","Data protection","Third-party services","Policy updates"],terms=["Services","Customer responsibilities","Payments","Shipping","Claims","Cancellations","Liability","Governing law"];const items=type==="privacy"?privacy:terms;const title=type==="privacy"?"Privacy Policy":"Terms of Service";return <><PageHero eyebrow="Legal information" title={title} text={`A structured draft for Cogent Distributing LLC's official ${title.toLowerCase()}.`}/><Breadcrumbs current={title}/><section className="py-20 lg:py-28"><div className="site-container grid gap-12 lg:grid-cols-[.35fr_1fr]"><aside><p className="border-l-2 border-signal pl-4 text-sm leading-6 text-muted-foreground">Draft structure only. This page has not been presented as reviewed by legal counsel.</p></aside><div className="space-y-12">{items.map((item,i)=><section key={item}><span className="service-index">0{i+1}</span><h2 className="mt-3 text-2xl font-bold text-navy">{item}</h2><p className="mt-4 leading-8 text-muted-foreground">Official language for this section will be added when supplied and approved by Cogent Distributing LLC.</p></section>)}<section><h2 className="text-2xl font-bold text-navy">Contact information</h2><p className="mt-4 leading-8 text-muted-foreground">Questions may be directed to <a className="font-bold text-brand" href="mailto:info@cogentdis.com">info@cogentdis.com</a>.</p></section></div></div></section></>}