/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesAutomobileLogisticsRouteImport } from './routes/services.automobile-logistics'
import { Route as ServicesDistributionRouteImport } from './routes/services.distribution'
import { Route as ServicesProcurementRouteImport } from './routes/services.procurement'
import { Route as ServicesShippingFreightRouteImport } from './routes/services.shipping-freight'
import { Route as ServicesWarehousingRouteImport } from './routes/services.warehousing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAutomobileLogisticsRoute =
  ServicesAutomobileLogisticsRouteImport.update({
    id: '/automobile-logistics',
    path: '/automobile-logistics',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesDistributionRoute = ServicesDistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesProcurementRoute = ServicesProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesShippingFreightRoute = ServicesShippingFreightRouteImport.update({
  id: '/shipping-freight',
  path: '/shipping-freight',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWarehousingRoute = ServicesWarehousingRouteImport.update({
  id: '/warehousing',
  path: '/warehousing',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/logistics': typeof LogisticsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/services/automobile-logistics': typeof ServicesAutomobileLogisticsRoute
  '/services/distribution': typeof ServicesDistributionRoute
  '/services/procurement': typeof ServicesProcurementRoute
  '/services/shipping-freight': typeof ServicesShippingFreightRoute
  '/services/warehousing': typeof ServicesWarehousingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/logistics': typeof LogisticsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/services/automobile-logistics': typeof ServicesAutomobileLogisticsRoute
  '/services/distribution': typeof ServicesDistributionRoute
  '/services/procurement': typeof ServicesProcurementRoute
  '/services/shipping-freight': typeof ServicesShippingFreightRoute
  '/services/warehousing': typeof ServicesWarehousingRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/logistics': typeof LogisticsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/services/automobile-logistics': typeof ServicesAutomobileLogisticsRoute
  '/services/distribution': typeof ServicesDistributionRoute
  '/services/procurement': typeof ServicesProcurementRoute
  '/services/shipping-freight': typeof ServicesShippingFreightRoute
  '/services/warehousing': typeof ServicesWarehousingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/logistics'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/services/automobile-logistics'
    | '/services/distribution'
    | '/services/procurement'
    | '/services/shipping-freight'
    | '/services/warehousing'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/logistics'
    | '/privacy'
    | '/terms'
    | '/services/automobile-logistics'
    | '/services/distribution'
    | '/services/procurement'
    | '/services/shipping-freight'
    | '/services/warehousing'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/logistics'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/services/automobile-logistics'
    | '/services/distribution'
    | '/services/procurement'
    | '/services/shipping-freight'
    | '/services/warehousing'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  LogisticsRoute: typeof LogisticsRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/automobile-logistics': {
      id: '/services/automobile-logistics'
      path: '/automobile-logistics'
      fullPath: '/services/automobile-logistics'
      preLoaderRoute: typeof ServicesAutomobileLogisticsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/distribution': {
      id: '/services/distribution'
      path: '/distribution'
      fullPath: '/services/distribution'
      preLoaderRoute: typeof ServicesDistributionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/procurement': {
      id: '/services/procurement'
      path: '/procurement'
      fullPath: '/services/procurement'
      preLoaderRoute: typeof ServicesProcurementRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/shipping-freight': {
      id: '/services/shipping-freight'
      path: '/shipping-freight'
      fullPath: '/services/shipping-freight'
      preLoaderRoute: typeof ServicesShippingFreightRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/warehousing': {
      id: '/services/warehousing'
      path: '/warehousing'
      fullPath: '/services/warehousing'
      preLoaderRoute: typeof ServicesWarehousingRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAutomobileLogisticsRoute: typeof ServicesAutomobileLogisticsRoute
  ServicesDistributionRoute: typeof ServicesDistributionRoute
  ServicesProcurementRoute: typeof ServicesProcurementRoute
  ServicesShippingFreightRoute: typeof ServicesShippingFreightRoute
  ServicesWarehousingRoute: typeof ServicesWarehousingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAutomobileLogisticsRoute: ServicesAutomobileLogisticsRoute,
  ServicesDistributionRoute: ServicesDistributionRoute,
  ServicesProcurementRoute: ServicesProcurementRoute,
  ServicesShippingFreightRoute: ServicesShippingFreightRoute,
  ServicesWarehousingRoute: ServicesWarehousingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  LogisticsRoute: LogisticsRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
